import fs from 'node:fs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const app=read('js/app.js'), core=read('js/app-core.js'), db=read('db.js'), migration=read('js/modules/data-migration.js'), html=read('index.html');
const manifest=JSON.parse(read('manifest.webmanifest')), version=read('VERSION.txt').trim();
for(const file of ['js/app.js','js/app-core.js','db.js','js/modules/print.js','js/modules/annotations.js','js/modules/organizer.js','js/modules/autosave.js','js/modules/data-migration.js','js/modules/testing.js']) execFileSync('node',['--check',path.join(root,file)]);
for(const file of ['modules/data-migration.js','modules/print.js','modules/annotations.js','modules/organizer.js','modules/autosave.js']) assert.match(app,new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
assert.match(core,/window\.MukorobApp\s*=\s*\{/);
assert.match(db,/const DB_VERSION\s*=\s*2/);
for(const store of ['settings','recent','annotations','users']) assert.match(db,new RegExp(`['"]${store}['"]`));
assert.match(migration,/PBKDF2-SHA256/); assert.match(migration,/AES-GCM/); assert.match(migration,/mkFirstRunRestore/); assert.match(migration,/active browser session token is never exported/);
assert.equal(manifest.version,'0.7.1'); assert.equal(version,'0.7.1'); assert.match(html,/type="module" src="js\/app\.js"/);
for(const id of ['btnPrint','btnCloseDocument','toolPageOrganizer','mukorobPrintSurface','autosaveStatus','bootstrapView']) assert.match(html,new RegExp(`id=["']${id}["']`));
const print=read('js/modules/print.js'); assert.match(print,/window\.print\(\)/); assert.doesNotMatch(print,/window\.open\s*\(/);
assert.match(read('js/modules/annotations.js'),/v07-resize-handle/); assert.match(read('js/modules/annotations.js'),/pointermove/);
assert.match(read('js/modules/organizer.js'),/draggable=true/); assert.match(read('js/modules/autosave.js'),/saveDraft/);
console.log('Mukorob PDF v0.7.1 structural smoke tests: PASS');
