import fs from 'node:fs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname);const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('js/app.js'),core=read('js/app-core.js'),db=read('js/db.js'),migration=read('js/modules/data-migration.js'),fixes=read('js/modules/v071-fixes.js'),html=read('index.html'),sw=read('sw.js');
const manifest=JSON.parse(read('manifest.webmanifest')),version=read('VERSION.txt').trim();
for(const file of ['js/app.js','js/app-core.js','js/db.js','js/modules/print.js','js/modules/annotations.js','js/modules/organizer.js','js/modules/autosave.js','js/modules/data-migration.js','js/modules/testing.js','js/modules/v071-fixes.js'])execFileSync('node',['--check',path.join(root,file)]);
for(const file of ['modules/data-migration.js','modules/print.js','modules/annotations.js','modules/organizer.js','modules/autosave.js','modules/v071-fixes.js'])assert.match(app,new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
assert.match(core,/window\.MukorobApp\s*=\s*\{/);assert.match(db,/const DB_VERSION\s*=\s*3/);
for(const store of ['settings','recent','annotations','users','recent_scoped','annotations_scoped','drafts','audit'])assert.match(db,new RegExp(`(?:['"]${store}['"]|\\b${store}:)`));
assert.match(migration,/PBKDF2-SHA256/);assert.match(migration,/AES-GCM/);assert.match(migration,/mkFirstRunRestore/);assert.match(migration,/active browser session token is never exported/);
assert.match(fixes,/v071Left/);assert.match(fixes,/v071Right/);assert.match(fixes,/v071-control/);assert.match(fixes,/removeAnn/);assert.match(fixes,/displayToDoc/);assert.match(fixes,/dashboardLogo/);assert.match(fixes,/loginBackgroundLogo/);assert.match(fixes,/loginIconLogo/);assert.match(fixes,/touchstart/);assert.match(fixes,/updateViaCache:'none'/);
assert.equal(manifest.version,'0.7.1');assert.equal(version,'0.7.1');assert.match(html,/type="module" src="js\/app\.js"/);assert.match(sw,/mukorob-pdf-v0\.7\.1-fix1/);assert.match(sw,/v071-fixes\.js/);
for(const id of ['btnPrint','btnCloseDocument','toolPageOrganizer','mukorobPrintSurface','autosaveStatus','bootstrapView'])assert.match(html,new RegExp(`id=["']${id}["']`));
const print=read('js/modules/print.js');assert.match(print,/window\.print\(\)/);assert.doesNotMatch(print,/window\.open\s*\(/);
assert.match(read('js/modules/annotations.js'),/v07-resize-handle/);assert.match(read('js/modules/annotations.js'),/pointermove/);assert.match(read('js/modules/organizer.js'),/draggable=true/);assert.match(read('js/modules/autosave.js'),/saveDraft/);
console.log('Mukorob PDF v0.7.1 structural smoke tests: PASS');
